### ISSUE TITLE
Renew blog.svg

### ISSUE THREAD

**Issue by cog25** [marshallku/marshallku#1]
![blog.svg](https://github.com/marshall-ku/marshall-ku/raw/master/assets/images/blog.svg)
<https://github.com/marshall-ku/marshall-ku/blob/master/assets/images/blog.svg>

해당 이미지에 `M` 을 새롭게 변경된 로고로 바꿔주세요!
~~너무 앏아요 ㅋㅋ~~

**Comment by marshallku** [comment]
수정하는 김에 다른 배지들과 같은 디자인으로 수정해뒀습니다!
